<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandsSeeder extends Seeder
{
    
    public function run(): void
    {
        $brand = [
            ['id' => 1, 'img' => null, 'name' => 'AC', 'alias' => null, 'popular'=> false],
            ['id' => 2, 'img' => null, 'name' => 'Acura', 'alias' => null, 'popular'=> false],
            ['id' => 3, 'img' => null, 'name' => 'AITO', 'alias' => null, 'popular'=> false],
            ['id' => 4, 'img' => null, 'name' => 'Alfa Romeo', 'alias' => null, 'popular'=> false],
            ['id' => 5, 'img' => null, 'name' => 'Alpina', 'alias' => null, 'popular'=> false],
            ['id' => 6, 'img' => null, 'name' => 'Arcfox', 'alias' => null, 'popular'=> false],
            ['id' => 7, 'img' => null, 'name' => 'Aro', 'alias' => null, 'popular'=> false],
            ['id' => 8, 'img' => null, 'name' => 'Asia', 'alias' => null, 'popular'=> false],
            ['id' => 9, 'img' => null, 'name' => 'Aston Martin', 'alias' => null, 'popular'=> false],
            ['id' => 10, 'img' => null, 'name' => 'Audi', 'alias' => null, 'popular'=> true],
            ['id' => 11, 'img' => null, 'name' => 'Avtr', 'alias' => null, 'popular'=> false],
            ['id' => 12, 'img' => null, 'name' => 'BAIC', 'alias' => null, 'popular'=> true],
            ['id' => 13, 'img' => null, 'name' => 'Baojun', 'alias' => null, 'popular'=> false],
            ['id' => 14, 'img' => null, 'name' => 'BAW', 'alias' => null, 'popular'=> false],
            ['id' => 15, 'img' => null, 'name' => 'Bentley', 'alias' => null, 'popular'=> false],
            ['id' => 16, 'img' => null, 'name' => 'BMW', 'alias' => null, 'popular'=> false],
            ['id' => 17, 'img' => null, 'name' => 'Brillance', 'alias' => null, 'popular'=> false],
            ['id' => 18, 'img' => null, 'name' => 'Buick', 'alias' => null, 'popular'=> false],
            ['id' => 19, 'img' => null, 'name' => 'BYD', 'alias' => null, 'popular'=> false],
            ['id' => 20, 'img' => null, 'name' => 'Cadillac', 'alias' => null, 'popular'=> false],
            ['id' => 21, 'img' => null, 'name' => 'Changan', 'alias' => null, 'popular'=> true],
            ['id' => 22, 'img' => null, 'name' => 'Changha', 'alias' => null, 'popular'=> false],
            ['id' => 23, 'img' => null, 'name' => 'Chery', 'alias' => null, 'popular'=> true],
            ['id' => 24, 'img' => null, 'name' => 'Chevrolet', 'alias' => null, 'popular'=> true],
            ['id' => 25, 'img' => null, 'name' => 'Chrysler', 'alias' => null, 'popular'=> false],
            ['id' => 26, 'img' => null, 'name' => 'Citroen', 'alias' => null, 'popular'=> true],
            ['id' => 27, 'img' => null, 'name' => 'Cupra', 'alias' => null, 'popular'=> false],
            ['id' => 28, 'img' => null, 'name' => 'Dacia', 'alias' => null, 'popular'=> false],
            ['id' => 29, 'img' => null, 'name' => 'Dadi', 'alias' => null, 'popular'=> false],
            ['id' => 30, 'img' => null, 'name' => 'Daewoo', 'alias' => null, 'popular'=> true],
            ['id' => 31, 'img' => null, 'name' => 'Daihatsu', 'alias' => null, 'popular'=> false],
            ['id' => 32, 'img' => null, 'name' => 'Daimler', 'alias' => null, 'popular'=> false],
            ['id' => 33, 'img' => null, 'name' => 'Datsun', 'alias' => null, 'popular'=> true],
            ['id' => 34, 'img' => null, 'name' => 'Dayun', 'alias' => null, 'popular'=> false],
            ['id' => 35, 'img' => null, 'name' => 'Derways', 'alias' => null, 'popular'=> false],
            ['id' => 36, 'img' => null, 'name' => 'Dodge', 'alias' => null, 'popular'=> false],
            ['id' => 37, 'img' => null, 'name' => 'Dongfeng', 'alias' => null, 'popular'=> false],
            ['id' => 38, 'img' => null, 'name' => 'DW Hower', 'alias' => null, 'popular'=> false],
            ['id' => 39, 'img' => null, 'name' => 'EXEED', 'alias' => null, 'popular'=> true],
            ['id' => 40, 'img' => null, 'name' => 'FAW', 'alias' => null, 'popular'=> true],
            ['id' => 41, 'img' => null, 'name' => 'Ferrari', 'alias' => null, 'popular'=> false],
            ['id' => 42, 'img' => null, 'name' => 'Fiat', 'alias' => null, 'popular'=> false],
            ['id' => 43, 'img' => null, 'name' => 'Ford', 'alias' => null, 'popular'=> true],
            ['id' => 44, 'img' => null, 'name' => 'Forthing', 'alias' => null, 'popular'=> false],
            ['id' => 45, 'img' => null, 'name' => 'Foton', 'alias' => null, 'popular'=> false],
            ['id' => 46, 'img' => null, 'name' => 'GAC', 'alias' => null, 'popular'=> false],
            ['id' => 47, 'img' => null, 'name' => 'Geely', 'alias' => null, 'popular'=> true],
            ['id' => 48, 'img' => null, 'name' => 'Genesis', 'alias' => null, 'popular'=> false],
            ['id' => 49, 'img' => null, 'name' => 'Geo', 'alias' => null, 'popular'=> false],
            ['id' => 50, 'img' => null, 'name' => 'GMC', 'alias' => null, 'popular'=> false],
            ['id' => 51, 'img' => null, 'name' => 'Great Wall', 'alias' => null, 'popular'=> false],
            ['id' => 52, 'img' => null, 'name' => 'Hafei', 'alias' => null, 'popular'=> false],
            ['id' => 53, 'img' => null, 'name' => 'Haima', 'alias' => null, 'popular'=> false],
            ['id' => 54, 'img' => null, 'name' => 'Haval', 'alias' => null, 'popular'=> true],
            ['id' => 55, 'img' => null, 'name' => 'Hawtai', 'alias' => null, 'popular'=> false],
            ['id' => 56, 'img' => null, 'name' => 'HiPhi', 'alias' => null, 'popular'=> false],
            ['id' => 57, 'img' => null, 'name' => 'Honda', 'alias' => null, 'popular'=> true],
            ['id' => 58, 'img' => null, 'name' => 'Hongpi', 'alias' => null, 'popular'=> false],
            ['id' => 59, 'img' => null, 'name' => 'Hozon', 'alias' => null, 'popular'=> false],
            ['id' => 60, 'img' => null, 'name' => 'Hummer', 'alias' => null, 'popular'=> false],
            ['id' => 61, 'img' => null, 'name' => 'Hyundai', 'alias' => null, 'popular'=> true],
            ['id' => 62, 'img' => null, 'name' => 'IM Motors', 'alias' => null, 'popular'=> false],
            ['id' => 63, 'img' => null, 'name' => 'Infiniti', 'alias' => null, 'popular'=> false],
            ['id' => 64, 'img' => null, 'name' => 'Iran Khodro', 'alias' => null, 'popular'=> false],
            ['id' => 65, 'img' => null, 'name' => 'Isuzu', 'alias' => null, 'popular'=> false],
            ['id' => 66, 'img' => null, 'name' => 'IVECO', 'alias' => null, 'popular'=> false],
            ['id' => 67, 'img' => null, 'name' => 'JAC', 'alias' => null, 'popular'=> false],
            ['id' => 68, 'img' => null, 'name' => 'Jaecco', 'alias' => null, 'popular'=> false],
            ['id' => 69, 'img' => null, 'name' => 'Jaguar', 'alias' => null, 'popular'=> false],
            ['id' => 70, 'img' => null, 'name' => 'Jeep', 'alias' => null, 'popular'=> false],
            ['id' => 71, 'img' => null, 'name' => 'Jetour', 'alias' => null, 'popular'=> false],
            ['id' => 72, 'img' => null, 'name' => 'Jetta', 'alias' => null, 'popular'=> false],
            ['id' => 73, 'img' => null, 'name' => 'Jindei', 'alias' => null, 'popular'=> false],
            ['id' => 74, 'img' => null, 'name' => 'Kaiyi', 'alias' => null, 'popular'=> false],
            ['id' => 75, 'img' => null, 'name' => 'Kia', 'alias' => null, 'popular'=> true],
            ['id' => 76, 'img' => null, 'name' => 'Lamborghini', 'alias' => null, 'popular'=> false],
            ['id' => 77, 'img' => null, 'name' => 'Lancia', 'alias' => null, 'popular'=> false],
            ['id' => 78, 'img' => null, 'name' => 'Land Rover', 'alias' => null, 'popular'=> true],
            ['id' => 79, 'img' => null, 'name' => 'Landwind', 'alias' => null, 'popular'=> false],
            ['id' => 80, 'img' => null, 'name' => 'Leapmotor', 'alias' => null, 'popular'=> false],
            ['id' => 81, 'img' => null, 'name' => 'Lexus', 'alias' => null, 'popular'=> false],
            ['id' => 82, 'img' => null, 'name' => 'Li', 'alias' => null, 'popular'=> false],
            ['id' => 83, 'img' => null, 'name' => 'Lifan', 'alias' => null, 'popular'=> true],
            ['id' => 84, 'img' => null, 'name' => 'Lincoln', 'alias' => null, 'popular'=> false],
            ['id' => 85, 'img' => null, 'name' => 'Livan', 'alias' => null, 'popular'=> false],
            ['id' => 86, 'img' => null, 'name' => 'Lotus', 'alias' => null, 'popular'=> false],
            ['id' => 87, 'img' => null, 'name' => 'Luxgen', 'alias' => null, 'popular'=> false],
            ['id' => 88, 'img' => null, 'name' => 'Lynk & Co', 'alias' => null, 'popular'=> false],
            ['id' => 89, 'img' => null, 'name' => 'Maserati', 'alias' => null, 'popular'=> false],
            ['id' => 90, 'img' => null, 'name' => 'Maxus', 'alias' => null, 'popular'=> false],
            ['id' => 91, 'img' => null, 'name' => 'Maybach', 'alias' => null, 'popular'=> false],
            ['id' => 92, 'img' => null, 'name' => 'Mazda', 'alias' => null, 'popular'=> true],
            ['id' => 93, 'img' => null, 'name' => 'McLaren', 'alias' => null, 'popular'=> false],
            ['id' => 94, 'img' => null, 'name' => 'Mercedes-Benz', 'alias' => null, 'popular'=> true],
            ['id' => 95, 'img' => null, 'name' => 'Mercury', 'alias' => null, 'popular'=> false],
            ['id' => 96, 'img' => null, 'name' => 'MG', 'alias' => null, 'popular'=> false],
            ['id' => 97, 'img' => null, 'name' => 'Mini', 'alias' => null, 'popular'=> false],
            ['id' => 98, 'img' => null, 'name' => 'Mitsubishi', 'alias' => null, 'popular'=> true],
            ['id' => 99, 'img' => null, 'name' => 'Mitsuoka', 'alias' => null, 'popular'=> false],
            ['id' => 100, 'img' => null, 'name' => 'Nio', 'alias' => null, 'popular'=> false],
            ['id' => 101, 'img' => null, 'name' => 'Nissan', 'alias' => null, 'popular'=> true],
            ['id' => 102, 'img' => null, 'name' => 'Oldmobile', 'alias' => null, 'popular'=> false],
            ['id' => 103, 'img' => null, 'name' => 'OMODA', 'alias' => null, 'popular'=> true],
            ['id' => 104, 'img' => null, 'name' => 'Opel', 'alias' => null, 'popular'=> true],
            ['id' => 105, 'img' => null, 'name' => 'Oshan', 'alias' => null, 'popular'=> false],
            ['id' => 106, 'img' => null, 'name' => 'Peugeot', 'alias' => null, 'popular'=> true],
            ['id' => 107, 'img' => null, 'name' => 'Plymouth', 'alias' => null, 'popular'=> false],
            ['id' => 108, 'img' => null, 'name' => 'Polestar', 'alias' => null, 'popular'=> false],
            ['id' => 109, 'img' => null, 'name' => 'Pontiac', 'alias' => null, 'popular'=> false],
            ['id' => 110, 'img' => null, 'name' => 'Porsche', 'alias' => null, 'popular'=> false],
            ['id' => 111, 'img' => null, 'name' => 'Proton', 'alias' => null, 'popular'=> false],
            ['id' => 112, 'img' => null, 'name' => 'RAM', 'alias' => null, 'popular'=> false],
            ['id' => 113, 'img' => null, 'name' => 'Ravon', 'alias' => null, 'popular'=> false],
            ['id' => 114, 'img' => null, 'name' => 'Renault', 'alias' => null, 'popular'=> true],
            ['id' => 115, 'img' => null, 'name' => 'Renault Samsung', 'alias' => null, 'popular'=> false],
            ['id' => 116, 'img' => null, 'name' => 'Rising Auto', 'alias' => null, 'popular'=> false],
            ['id' => 117, 'img' => null, 'name' => 'Roewe', 'alias' => null, 'popular'=> false],
            ['id' => 118, 'img' => null, 'name' => 'Rolls-Royse', 'alias' => null, 'popular'=> false],
            ['id' => 119, 'img' => null, 'name' => 'Rover', 'alias' => null, 'popular'=> false],
            ['id' => 120, 'img' => null, 'name' => 'Saab', 'alias' => null, 'popular'=> false],
            ['id' => 121, 'img' => null, 'name' => 'Saturn', 'alias' => null, 'popular'=> false],
            ['id' => 122, 'img' => null, 'name' => 'Scion', 'alias' => null, 'popular'=> false],
            ['id' => 123, 'img' => null, 'name' => 'SEAT', 'alias' => null, 'popular'=> false],
            ['id' => 124, 'img' => null, 'name' => 'Seres', 'alias' => null, 'popular'=> false],
            ['id' => 125, 'img' => null, 'name' => 'Shuanghuan', 'alias' => null, 'popular'=> false],
            ['id' => 126, 'img' => null, 'name' => 'Skoda', 'alias' => null, 'popular'=> true],
            ['id' => 127, 'img' => null, 'name' => 'Skywell', 'alias' => null, 'popular'=> false],
            ['id' => 128, 'img' => null, 'name' => 'Smart', 'alias' => null, 'popular'=> false],
            ['id' => 129, 'img' => null, 'name' => 'Soueart', 'alias' => null, 'popular'=> false],
            ['id' => 130, 'img' => null, 'name' => 'SsangYong', 'alias' => null, 'popular'=> false],
            ['id' => 131, 'img' => null, 'name' => 'Subaru', 'alias' => null, 'popular'=> true],
            ['id' => 132, 'img' => null, 'name' => 'Suzuki', 'alias' => null, 'popular'=> true],
            ['id' => 133, 'img' => null, 'name' => 'Tank', 'alias' => null, 'popular'=> false],
            ['id' => 134, 'img' => null, 'name' => 'Tesla', 'alias' => null, 'popular'=> false],
            ['id' => 135, 'img' => null, 'name' => 'Tianma', 'alias' => null, 'popular'=> false],
            ['id' => 136, 'img' => null, 'name' => 'Toyota', 'alias' => null, 'popular'=> true],
            ['id' => 137, 'img' => null, 'name' => 'Venicia', 'alias' => null, 'popular'=> false],
            ['id' => 138, 'img' => null, 'name' => 'Volkswagen', 'alias' => null, 'popular'=> true],
            ['id' => 139, 'img' => null, 'name' => 'Volvo', 'alias' => null, 'popular'=> true],
            ['id' => 140, 'img' => null, 'name' => 'Vortex', 'alias' => null, 'popular'=> false],
            ['id' => 141, 'img' => null, 'name' => 'Voyah', 'alias' => null, 'popular'=> false],
            ['id' => 142, 'img' => null, 'name' => 'Weltmeister', 'alias' => null, 'popular'=> false],
            ['id' => 143, 'img' => null, 'name' => 'WEY', 'alias' => null, 'popular'=> false],
            ['id' => 144, 'img' => null, 'name' => 'Wuling', 'alias' => null, 'popular'=> false],
            ['id' => 145, 'img' => null, 'name' => 'Xin Kai', 'alias' => null, 'popular'=> false],
            ['id' => 146, 'img' => null, 'name' => 'Xpeng', 'alias' => null, 'popular'=> false],
            ['id' => 147, 'img' => null, 'name' => 'Zeekr', 'alias' => null, 'popular'=> false],
            ['id' => 148, 'img' => null, 'name' => 'Zotye', 'alias' => null, 'popular'=> false],
            ['id' => 149, 'img' => null, 'name' => 'ZX', 'alias' => null, 'popular'=> false],
            ['id' => 150, 'img' => null, 'name' => 'Evolute', 'alias' => null, 'popular'=> false],
            ['id' => 151, 'img' => null, 'name' => 'Аурус', 'alias' => null, 'popular'=> false],
            ['id' => 152, 'img' => null, 'name' => 'Богдан', 'alias' => null, 'popular'=> false],
            ['id' => 153, 'img' => null, 'name' => 'ГАЗ', 'alias' => null, 'popular'=> true],
            ['id' => 154, 'img' => null, 'name' => 'Донинвест', 'alias' => null, 'popular'=> false],
            ['id' => 155, 'img' => null, 'name' => 'ЗАЗ', 'alias' => null, 'popular'=> true],
            ['id' => 156, 'img' => null, 'name' => 'ЗИЛ', 'alias' => null, 'popular'=> false],
            ['id' => 157, 'img' => null, 'name' => 'ЗиС', 'alias' => null, 'popular'=> false],
            ['id' => 158, 'img' => null, 'name' => 'ИЖ', 'alias' => null, 'popular'=> false],
            ['id' => 159, 'img' => null, 'name' => 'Лада', 'alias' => null, 'popular'=> true],
            ['id' => 160, 'img' => null, 'name' => 'ЛуАЗ', 'alias' => null, 'popular'=> false],
            ['id' => 161, 'img' => null, 'name' => 'Москвич', 'alias' => null, 'popular'=> false],
            ['id' => 162, 'img' => null, 'name' => 'ТагАЗ', 'alias' => null, 'popular'=> false],
            ['id' => 163, 'img' => null, 'name' => 'УАЗ', 'alias' => null, 'popular'=> true],
            ['id' => 164, 'img' => null, 'name' => 'Прочие авто', 'alias' => null, 'popular'=> false],
        ];

        DB::table('brands')->insert($brand);
    }
}
