<?php


namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandsSeeder extends Seeder
{
    
    public function run(): void
    {
        $brand = [
            [
                'id' => 1, 
               'img_light' => null,
               'img_dark' => null, 
               'name' => 'AC', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 2, 
               'img_light' => "brands/acura.png",
               'img_dark' => null, 
               'name' => 'Acura', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 3, 
               'img_light' => null,
               'img_dark' => null,
               'name' => 'AITO', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 4, 
               'img_light' => "brands/alfa-romeo.png",
               'img_dark' => null,
               'name' => 'Alfa Romeo', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 5, 
               'img_light' => "brands/alpina.png",
               'img_dark' => null,
               'name' => 'Alpina', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 6, 
               'img_light' => null,
               'img_dark' => null,
               'name' => 'Arcfox', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 7, 
               'img_light' => "brands/aro-light.png",
               'img_dark' => "brands/aro-dark.png",
               'name' => 'Aro', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 8, 
               'img_light' => "brands/asia.png",
               'img_dark' => null,
               'name' => 'Asia', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 9, 
               'img_light' => "brands/astonmartin-light.png",
               'img_dark' => "brands/astonmartin-dark.png",
               'name' => 'Aston Martin', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 10,
                'img_light' => "brands/audi-light.png",
                'img_dark' => "brands/audi-dark.png", 
                'name' => 'Audi', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 11,
                'img_light' => "brands/avatr-light.png",
                'img_dark' => "brands/avatr-dark.png", 
                'name' => 'Avtr', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 12,
                'img_light' => "brands/baic.png",
                'img_dark' => null, 
                'name' => 'BAIC', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 13,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Baojun', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 14,
                'img_light' => "brands/baw.png",
                'img_dark' => null, 
                'name' => 'BAW', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 15,
                'img_light' => "brands/bentley.png",
                'img_dark' => null, 
                'name' => 'Bentley', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 16,
                'img_light' => "brands/bmw-light.png",
                'img_dark' => "brands/bmw-dark.png", 
                'name' => 'BMW', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 17,
                'img_light' => "brands/brilliance.png",
                'img_dark' => null, 
                'name' => 'Brillance', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 18,
                'img_light' => "brands/buick.png",
                'img_dark' => null, 
                'name' => 'Buick', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 19,
                'img_light' => "brands/byd.png",
                'img_dark' => null, 
                'name' => 'BYD', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 20,
                'img_light' => "brands/cadillac.png",
                'img_dark' => null, 
                'name' => 'Cadillac', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 21,
                'img_light' => "brands/changan.png",
                'img_dark' => null, 
                'name' => 'Changan', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 22,
                'img_light' => "brands/changhe.png",
                'img_dark' => null, 
                'name' => 'Changhe', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 23,
                'img_light' => "brands/chery.png",
                'img_dark' => null, 
                'name' => 'Chery', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 24,
                'img_light' => "brands/chevrolet.png",
                'img_dark' => null, 
                'name' => 'Chevrolet', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => true,
                'popular_passenger' => true,    
            ],
            [
                'id' => 25,
                'img_light' => "brands/chrysler.png",
                'img_dark' => null, 
                'name' => 'Chrysler', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 26,
                'img_light' => "brands/citroen-light.png",
                'img_dark' => "brands/citroen-dark.png", 
                'name' => 'Citroen', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 27,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Cupra', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 28,
                'img_light' => "brands/dacia-light.png",
                'img_dark' => "brands/dacia-dark.png", 
                'name' => 'Dacia', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 29,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Dadi', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 30,
                'img_light' => "brands/daewoo.png",
                'img_dark' => null, 
                'name' => 'Daewoo', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 31,
                'img_light' => "brands/daihatsu.png",
                'img_dark' => null, 
                'name' => 'Daihatsu', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 32,
                'img_light' => "brands/daimler.png",
                'img_dark' => null, 
                'name' => 'Daimler', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 33,
                'img_light' => "brands/datsun.png",
                'img_dark' => null, 
                'name' => 'Datsun', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 34,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Dayun', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 35,
                'img_light' => "brands/derways.png",
                'img_dark' => null, 
                'name' => 'Derways', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 36,
                'img_light' => "brands/dodge-light.png",
                'img_dark' => "brands/dodge-dark.png", 
                'name' => 'Dodge', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 37,
                'img_light' => "brands/dongfeng.png",
                'img_dark' => null, 
                'name' => 'Dongfeng', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 38,
                'img_light' => "brands/dw-hower.png",
                'img_dark' => null, 
                'name' => 'DW Hower', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 39,
                'img_light' => "brands/exeed.png",
                'img_dark' => null, 
                'name' => 'EXEED', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 40,
                'img_light' => "brands/faw.png",
                'img_dark' => null, 
                'name' => 'FAW', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 41,
                'img_light' => "brands/ferrari.png",
                'img_dark' => null, 
                'name' => 'Ferrari', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 42,
                'img_light' => "brands/fiat.png",
                'img_dark' => null, 
                'name' => 'Fiat', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 43,
                'img_light' => "brands/ford.png",
                'img_dark' => null, 
                'name' => 'Ford', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => true,
                'popular_passenger' => true,    
            ],
            [
                'id' => 44,
                'img_light' => "brands/forthing.png",
                'img_dark' => null, 
                'name' => 'Forthing', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 45,
                'img_light' => "brands/foton.png",
                'img_dark' => null, 
                'name' => 'Foton', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 46,
                'img_light' => "brands/gac.png",
                'img_dark' => null, 
                'name' => 'GAC', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 47,
                'img_light' => "brands/geely.png",
                'img_dark' => null, 
                'name' => 'Geely', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 48,
                'img_light' => "brands/genesis.png",
                'img_dark' => null, 
                'name' => 'Genesis', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 49,
                'img_light' => "brands/geo.png",
                'img_dark' => null, 
                'name' => 'Geo', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 50,
                'img_light' => "brands/gmc.png",
                'img_dark' => null, 
                'name' => 'GMC', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 51,
                'img_light' => "brands/great-wall.png",
                'img_dark' => null, 
                'name' => 'Great Wall', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 52,
                'img_light' => "brands/hafei.png",
                'img_dark' => null, 
                'name' => 'Hafei', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 53,
                'img_light' => "brands/haima.png",
                'img_dark' => null, 
                'name' => 'Haima', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 54,
                'img_light' => "brands/haval.png",
                'img_dark' => null, 
                'name' => 'Haval', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 55,
                'img_light' => "brands/hawtai.png",
                'img_dark' => null, 
                'name' => 'Hawtai', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 56,
                'img_light' => "brands/hiphi-light.png",
                'img_dark' => "brands/hiphi-dark.png", 
                'name' => 'HiPhi', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 57,
                'img_light' => "brands/honda.png",
                'img_dark' => null, 
                'name' => 'Honda', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 58,
                'img_light' => "brands/hongqi.png",
                'img_dark' => null, 
                'name' => 'Hongpi', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 59,
                'img_light' => "brands/hozon-light.png",
                'img_dark' => "brands/hozon-dark.png", 
                'name' => 'Hozon', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 60,
                'img_light' => "brands/hummer-light.png",
                'img_dark' => "brands/hummer-dark.png", 
                'name' => 'Hummer', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 61,
                'img_light' => "brands/hyundai.png",
                'img_dark' => null, 
                'name' => 'Hyundai', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => true,
                'popular_passenger' => true,    
            ],
            [
                'id' => 62,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'IM Motors', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 63,
                'img_light' => "brands/infiniti.png",
                'img_dark' => null, 
                'name' => 'Infiniti', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 64,
                'img_light' => "brands/iran-khodro.png",
                'img_dark' => null, 
                'name' => 'Iran Khodro', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 65,
                'img_light' => "brands/isuzu.png",
                'img_dark' => null, 
                'name' => 'Isuzu', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 66,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'IVECO', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 67,
                'img_light' => "brands/jac.png",
                'img_dark' => null, 
                'name' => 'JAC', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 68,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Jaecco', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 69,
                'img_light' => "brands/jaguar.png",
                'img_dark' => null, 
                'name' => 'Jaguar', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 70,
                'img_light' => "brands/jeep.png",
                'img_dark' => null, 
                'name' => 'Jeep', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 71,
                'img_light' => "brands/jetour-light.png",
                'img_dark' => "brands/jetour-dark.png", 
                'name' => 'Jetour', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 72,
                'img_light' => "brands/jetta-light.png",
                'img_dark' => "brands/jetta-dark.png", 
                'name' => 'Jetta', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 73,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Jindei', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 74,
                'img_light' => "brands/kaiyi-light.png",
                'img_dark' => "brands/kaiyi-dark.png", 
                'name' => 'Kaiyi', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 75,
                'img_light' => "brands/kia-light.png",
                'img_dark' => "brands/kia-dark.png", 
                'name' => 'Kia', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 76,
                'img_light' => "brands/lamborghini.png",
                'img_dark' => null, 
                'name' => 'Lamborghini', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 77,
                'img_light' => "brands/lancia.png",
                'img_dark' => null, 
                'name' => 'Lancia', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 78,
                'img_light' => "brands/land-rover.png",
                'img_dark' => null, 
                'name' => 'Land Rover', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 79,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Landwind', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 80,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Leapmotor', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 81,
                'img_light' => "brands/lexus.png",
                'img_dark' => null, 
                'name' => 'Lexus', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 82,
                'img_light' => "brands/li-light.png",
                'img_dark' => "brands/li-dark.png", 
                'name' => 'Li', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 83,
                'img_light' => "brands/lifan.png",
                'img_dark' => null, 
                'name' => 'Lifan', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,    
            ],
            [
                'id' => 84,
                'img_light' => "brands/lincoln-light.png",
                'img_dark' => "brands/lincoln-dark.png", 
                'name' => 'Lincoln', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 85,
                'img_light' => "brands/livan-light.png",
                'img_dark' => "brands/livan-dark.png", 
                'name' => 'Livan', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 86,
                'img_light' => "brands/lotus.png",
                'img_dark' => null, 
                'name' => 'Lotus', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 87,
                'img_light' => "brands/luxgen.png",
                'img_dark' => null, 
                'name' => 'Luxgen', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 88,
                'img_light' => "brands/lynk_and_co-light.png",
                'img_dark' => "brands/lynk_and_co-dark.png", 
                'name' => 'Lynk & Co', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 89,
                'img_light' => "brands/maserati-light.png",
                'img_dark' => "brands/maserati-dark.png", 
                'name' => 'Maserati', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 90,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Maxus', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 91,
                'img_light' => "brands/maybach.png",
                'img_dark' => null, 
                'name' => 'Maybach', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,    
            ],
            [
                'id' => 92,
                'img_light' => "brands/mazda.png",
                'img_dark' => null, 
                'name' => 'Mazda', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,
            ],
            [
                'id' => 93,
                'img_light' => "brands/mclaren-light.png",
                'img_dark' => "brands/mclaren-dark.png", 
                'name' => 'McLaren', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 94,
                'img_light' => "brands/mercedes-benz.png",
                'img_dark' => null, 
                'name' => 'Mercedes-Benz', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => true,
                'popular_passenger' => true,
            ],
            [
                'id' => 95,
                'img_light' => "brands/mercury.png",
                'img_dark' => null, 
                'name' => 'Mercury', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 96,
                'img_light' => "brands/mg-light.png",
                'img_dark' => "brands/mg-dark.png", 
                'name' => 'MG', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 97,
                'img_light' => "brands/mini-light.png",
                'img_dark' => "brands/mini-dark.png", 
                'name' => 'Mini', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 98,
                'img_light' => "brands/mitsubishi.png",
                'img_dark' => null, 
                'name' => 'Mitsubishi', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => true,
                'popular_passenger' => true,
            ],
            [
                'id' => 99,
                'img_light' => "brands/mitsuoka-light.png",
                'img_dark' => "brands/mitsuoka-dark.png", 
                'name' => 'Mitsuoka', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 100, 
                'img_light' => "brands/nio-light.png",
                'img_dark' => "brands/nio-dark.png", 
               'name' => 'Nio', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 101, 
                'img_light' => "brands/nissan-light.png",
                'img_dark' => "brands/nissan-dark.png", 
                'name' => 'Nissan', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => true,
                'popular_passenger' => true,
            ],
            [
                'id' => 102, 
                'img_light' => "brands/oldsmobile.png",
                'img_dark' => null, 
                'name' => 'Oldsmobile', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 103, 
                'img_light' => "brands/omoda-light.png",
                'img_dark' => "brands/omoda-dark.png", 
                'name' => 'OMODA', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => true,
            ],
            [
                'id' => 104,
                'img_light' => "brands/opel-light.png",
                'img_dark' => "brands/opel-dark.png", 
                'name' => 'Opel', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,
            ],
            [
                'id' => 105,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Oshan', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 106,
                'img_light' => "brands/peugeot.png",
                'img_dark' => null, 
                'name' => 'Peugeot', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 2,
                'popular_cargo' => false,
                'popular_passenger' => true,
            ],
            [
                'id' => 107, 
                'img_light' => "brands/plymouth.png",
                'img_dark' => null, 
                'name' => 'Plymouth', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 108, 
                'img_light' => "brands/polestar.png",
                'img_dark' => null, 
                'name' => 'Polestar', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 109, 
                'img_light' => "brands/pontiac-light.png",
                'img_dark' => "brands/pontiac-dark.png", 
                'name' => 'Pontiac', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 110,
                'img_light' => "brands/porsche.png",
                'img_dark' => null, 
                'name' => 'Porsche', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 111, 
                'img_light' => "brands/proton.png",
                'img_dark' => null, 
                'name' => 'Proton', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 112, 
                'img_light' => "brands/ram.png",
                'img_dark' => null, 
                'name' => 'RAM', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 1,  
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 113,
               'img_light' => "brands/ravon.png",
               'img_dark' => null, 
               'name' => 'Ravon', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 114,
               'img_light' => "brands/renault-light.png",
               'img_dark' => "brands/renault-dark.png", 
               'name' => 'Renault', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => true,
               'popular_passenger' => true,
            ],
            [
                'id' => 115,
               'img_light' => "brands/renault-samsung.png",
               'img_dark' => null, 
               'name' => 'Renault Samsung', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 116,
               'img_light' => null,
               'img_dark' => null, 
               'name' => 'Rising Auto', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 117,
               'img_light' => "brands/roewe-light.png",
               'img_dark' => "brands/roewe-dark.png", 
               'name' => 'Roewe', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 118,
               'img_light' => "brands/rolls-royce.png",
               'img_dark' => null, 
               'name' => 'Rolls-Royse', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 119,
               'img_light' => "brands/rover.png",
               'img_dark' => null, 
               'name' => 'Rover', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 120,
               'img_light' => "brands/saab.png",
               'img_dark' => null, 
               'name' => 'Saab', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 121,
               'img_light' => "brands/saturn.png",
               'img_dark' => null, 
               'name' => 'Saturn', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 122,
               'img_light' => "brands/scion.png",
               'img_dark' => null, 
               'name' => 'Scion', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 123,
               'img_light' => "brands/seat.png",
               'img_dark' => null, 
               'name' => 'SEAT', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 124,
               'img_light' => null,
               'img_dark' => null, 
               'name' => 'Seres', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 125,
               'img_light' => "brands/shuanghuan.png",
               'img_dark' => null, 
               'name' => 'Shuanghuan', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 126,
               'img_light' => "brands/skoda.png",
               'img_dark' => null, 
               'name' => 'Skoda', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => true,
            ],
            [
                'id' => 127,
               'img_light' => "brands/skywell.png",
               'img_dark' => null, 
               'name' => 'Skywell', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 128,
               'img_light' => "brands/smart.png",
               'img_dark' => null, 
               'name' => 'Smart', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 129,
               'img_light' => "brands/soueast.png",
               'img_dark' => null, 
               'name' => 'Soueast', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 130,
               'img_light' => "brands/ssangyong.png",
               'img_dark' => null, 
               'name' => 'SsangYong', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 131,
               'img_light' => "brands/subaru.png",
               'img_dark' => null, 
               'name' => 'Subaru', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => true,
               'popular_passenger' => true,
            ],
            [
                'id' => 132,
               'img_light' => "brands/suzuki.png",
               'img_dark' => null, 
               'name' => 'Suzuki', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => true,
               'popular_passenger' => true,
            ],
            [
                'id' => 133,
               'img_light' => "brands/tank-light.png",
               'img_dark' => "brands/tank-dark.png", 
               'name' => 'Tank', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 134,
               'img_light' => "brands/tesla.png",
               'img_dark' => null, 
               'name' => 'Tesla', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 135,
               'img_light' => "brands/tianma.png",
               'img_dark' => null, 
               'name' => 'Tianma', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 136,
               'img_light' => "brands/toyota-light.png",
               'img_dark' => "brands/toyota-dark.png", 
               'name' => 'Toyota', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => true,
               'popular_passenger' => true,
            ],
            [
                'id' => 137,
               'img_light' => null,
               'img_dark' => null, 
               'name' => 'Venicia', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 138,
               'img_light' => "brands/volkswagen.png",
               'img_dark' => null, 
               'name' => 'Volkswagen', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => true,
               'popular_passenger' => true,
            ],
            [
                'id' => 139,
               'img_light' => "brands/volvo-light.png",
               'img_dark' => "brands/volvo-dark.png", 
               'name' => 'Volvo', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => true,
            ],
            [
                'id' => 140,
               'img_light' => "brands/vortex-light.png",
               'img_dark' => "brands/vortex-dark.png", 
               'name' => 'Vortex', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 141,
               'img_light' => "brands/voyah-light.png",
               'img_dark' => "brands/voyah-dark.png",  
               'name' => 'Voyah', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 142,
               'img_light' => "brands/weltmeister-light.png",
               'img_dark' => "brands/weltmeister-dark.png",  
               'name' => 'Weltmeister', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 143,
               'img_light' => null,
               'img_dark' => null, 
               'name' => 'WEY', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 144,
               'img_light' => null,
               'img_dark' => null, 
               'name' => 'Wuling', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 145,
               'img_light' => "brands/xin-kai-light.png",
               'img_dark' => "brands/xin-kai-dark.png",  
               'name' => 'Xin Kai', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 146,
               'img_light' => "brands/xpeng-light.png",
               'img_dark' => "brands/xpeng-dark.png",  
               'name' => 'Xpeng', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 147,
               'img_light' => "brands/zeekr-light.png",
               'img_dark' => "brands/zeekr-dark.png",  
               'name' => 'Zeekr', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 148,
               'img_light' => "brands/zotye.png",
               'img_dark' => null, 
               'name' => 'Zotye', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 149,
               'img_light' => "brands/zx.png",
               'img_dark' => null, 
               'name' => 'ZX', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 150,
               'img_light' => "brands/evolute-light.png",
               'img_dark' => "brands/evolute-dark.png", 
               'name' => 'Evolute', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 151,
               'img_light' => "brands/aurus.png",
               'img_dark' => null, 
               'name' => 'Аурус', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 152,
               'img_light' => "brands/bogdan.png",
               'img_dark' => null, 
               'name' => 'Богдан', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 153,
               'img_light' => "brands/gaz.png",
               'img_dark' => null, 
               'name' => 'ГАЗ', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => true,
            ],
            [
                'id' => 154,
               'img_light' => "brands/doninvest.png",
               'img_dark' => null, 
               'name' => 'Донинвест', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 155,
               'img_light' => "brands/zaz.png",
               'img_dark' => null, 
               'name' => 'ЗАЗ', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => true,
            ],
            [
                'id' => 156,
               'img_light' => "brands/zil-light.png",
               'img_dark' => "brands/zil-dark.png", 
               'name' => 'ЗИЛ', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 157,
               'img_light' => null,
               'img_dark' => null, 
               'name' => 'ЗиС', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 158,
               'img_light' => "brands/izh.png",
               'img_dark' => null, 
               'name' => 'ИЖ', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 159,
               'img_light' => "brands/lada.png",
               'img_dark' => null, 
               'name' => 'Лада', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => true,
               'popular_passenger' => true,
            ],
            [
                'id' => 160,
               'img_light' => "brands/luaz.png",
               'img_dark' => null, 
               'name' => 'ЛуАЗ', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 161,
               'img_light' => "brands/moskvich.png",
               'img_dark' => null, 
               'name' => 'Москвич', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 162,
               'img_light' => "brands/tagaz.png",
               'img_dark' => null, 
               'name' => 'ТагАЗ', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 163,
               'img_light' => "brands/uaz.png",
               'img_dark' => null, 
               'name' => 'УАЗ', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 2,
               'popular_cargo' => false,
               'popular_passenger' => true,
            ],
            [
                'id' => 164,
               'img_light' => null,
               'img_dark' => null, 
               'name' => 'Прочие авто', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 1,  
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 165,
               'img_light' => null,
               'img_dark' => null, 
               'name' => 'Avia', 
               'link_passenger' => null, 
               'link_cargo' => null,  
               'type'=> 3,
               'popular_cargo' => false,
               'popular_passenger' => false,
            ],
            [
                'id' => 166,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Bajaja', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 167,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Barkas', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 168,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Bedford', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 169,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Bremach', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 170,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'CAMC', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,
            ],
            [
                'id' => 171,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'DAF', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 172,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'ERF', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 173,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Freightliner', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 174,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Golden Dragon', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 175,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Groz', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 176,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Higer', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 177,
                'img_light' => "brands/hino-light.png",
                'img_dark' => "brands/hino-dark.png", 
                'name' => 'Hino', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 178,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Hongyan', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 179,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Howo', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 180,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'IFA', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false,  
            ],
            [
                'id' => 181,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Ikarus', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 182,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'JBC', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 183,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'JMC', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 184,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Kenworth', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 185,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'King Long', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 186,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'LDV', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 187,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'MAN', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 188,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Marcopolo', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 189,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Naveco', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 190,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Neoplan', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 191,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Nysa', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 192,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Peterbilt', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 193,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Piggio', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 194,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Sany', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 195,
                'img_light' => "brands/scania.png",
                'img_dark' => null, 
                'name' => 'Scania', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 196,
                'img_light' => "brands/shacman-light.png",
                'img_dark' => "brands/shacman-dark.png", 
                'name' => 'Shacman (Shaanxi)', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 197,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'SITRAK', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 198,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Sollers', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 199,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'TATA', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 200,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Tatra', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 201,
                'img_light' => null,
                'img_dark' => null,
                'name' => 'Van Hool', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 202,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Wuling', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 203,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Yuejin', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 204,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Yutong', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 205,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Zhong Tong', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 206,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Zuk', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 207,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'БАЗ', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 208,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'ВИС', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 209,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Гуран', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 210,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'ЕрАЗ', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 211,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'КАвЗ', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 212,
                'img_light' => "brands/kamaz.png",
                'img_dark' => null, 
                'name' => 'КамАЗ', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 213,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'КрАЗ', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 214,
                'img_light' => "brands/maz.png",
                'img_dark' => null, 
                'name' => 'МАЗ', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 215,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'Неман', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 216,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'НефАЗ', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 217,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'РАФ', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 218,
                'img_light' => "brands/ural.png",
                'img_dark' => null, 
                'name' => 'Урал', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
            [
                'id' => 219,
                'img_light' => null,
                'img_dark' => null, 
                'name' => 'International', 
                'link_passenger' => null, 
                'link_cargo' => null,  
                'type'=> 3,
                'popular_cargo' => false,
                'popular_passenger' => false, 
            ],
        ];

        DB::table('brands')->insert($brand);
    }
}
