<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandsSeeder extends Seeder
{
    
    public function run(): void
    {
        $brand = [
            ['id' => 1, 'img_light' => null,'img_dark' => null, 'name' => 'AC', 'alias' => null, 'popular'=> false],
            ['id' => 2, 'img_light' => "brands/acura.png",'img_dark' => null, 'name' => 'Acura', 'alias' => null, 'popular'=> false],
            ['id' => 3, 'img_light' => null,'img_dark' => null,'name' => 'AITO', 'alias' => null, 'popular'=> false],
            ['id' => 4, 'img_light' => "brands/alfa-romeo.png",'img_dark' => null,'name' => 'Alfa Romeo', 'alias' => null, 'popular'=> false],
            ['id' => 5, 'img_light' => "brands/alpina.png",'img_dark' => null,'name' => 'Alpina', 'alias' => null, 'popular'=> false],
            ['id' => 6, 'img_light' => null,'img_dark' => null,'name' => 'Arcfox', 'alias' => null, 'popular'=> false],
            ['id' => 7, 'img_light' => "brands/aro-light.png",'img_dark' => "brands/aro-dark.png",'name' => 'Aro', 'alias' => null, 'popular'=> false],
            ['id' => 8, 'img_light' => "brands/asia.png",'img_dark' => null,'name' => 'Asia', 'alias' => null, 'popular'=> false],
            ['id' => 9, 'img_light' => "brands/astonmartin-light.png",'img_dark' => "brands/astonmartin-dark.png",'name' => 'Aston Martin', 'alias' => null, 'popular'=> false],
            ['id' => 10, 'img_light' => "brands/audi-light.png",'img_dark' => "brands/audi-dark.png", 'name' => 'Audi', 'alias' => null, 'popular'=> true],
            ['id' => 11, 'img_light' => "brands/avatr-light.png",'img_dark' => "brands/avatr-dark.png", 'name' => 'Avtr', 'alias' => null, 'popular'=> false],
            ['id' => 12, 'img_light' => "brands/baic.png",'img_dark' => null, 'name' => 'BAIC', 'alias' => null, 'popular'=> true],
            ['id' => 13, 'img_light' => null,'img_dark' => null, 'name' => 'Baojun', 'alias' => null, 'popular'=> false],
            ['id' => 14, 'img_light' => "brands/baw.png",'img_dark' => null, 'name' => 'BAW', 'alias' => null, 'popular'=> false],
            ['id' => 15, 'img_light' => "brands/bently.png",'img_dark' => null, 'name' => 'Bentley', 'alias' => null, 'popular'=> false],
            ['id' => 16, 'img_light' => "brands/bmw-light.png",'img_dark' => "brands/bmw-dark.png", 'name' => 'BMW', 'alias' => null, 'popular'=> false],
            ['id' => 17, 'img_light' => "brands/brilliance.png",'img_dark' => null, 'name' => 'Brillance', 'alias' => null, 'popular'=> false],
            ['id' => 18, 'img_light' => "brands/buick.png",'img_dark' => null, 'name' => 'Buick', 'alias' => null, 'popular'=> false],
            ['id' => 19, 'img_light' => "brands/byd.png",'img_dark' => null, 'name' => 'BYD', 'alias' => null, 'popular'=> false],
            ['id' => 20, 'img_light' => "brands/cadilac.png",'img_dark' => null, 'name' => 'Cadillac', 'alias' => null, 'popular'=> false],
            ['id' => 21, 'img_light' => "brands/changan.png",'img_dark' => null, 'name' => 'Changan', 'alias' => null, 'popular'=> true],
            ['id' => 22, 'img_light' => "brands/changhe.png",'img_dark' => null, 'name' => 'Changhe', 'alias' => null, 'popular'=> false],
            ['id' => 23, 'img_light' => "brands/chery.png",'img_dark' => null, 'name' => 'Chery', 'alias' => null, 'popular'=> true],
            ['id' => 24, 'img_light' => "brands/chevrolet.png",'img_dark' => null, 'name' => 'Chevrolet', 'alias' => null, 'popular'=> true],
            ['id' => 25, 'img_light' => "brands/chrysler.png",'img_dark' => null, 'name' => 'Chrysler', 'alias' => null, 'popular'=> false],
            ['id' => 26, 'img_light' => "brands/citroen-light.png",'img_dark' => "brands/citroen-dark.png", 'name' => 'Citroen', 'alias' => null, 'popular'=> true],
            ['id' => 27, 'img_light' => null,'img_dark' => null, 'name' => 'Cupra', 'alias' => null, 'popular'=> false],
            ['id' => 28, 'img_light' => "brands/dacia-light.png",'img_dark' => "brands/dacia-dark.png", 'name' => 'Dacia', 'alias' => null, 'popular'=> false],
            ['id' => 29, 'img_light' => null,'img_dark' => null, 'name' => 'Dadi', 'alias' => null, 'popular'=> false],
            ['id' => 30, 'img_light' => "brands/daewoo.png",'img_dark' => null, 'name' => 'Daewoo', 'alias' => null, 'popular'=> true],
            ['id' => 31, 'img_light' => "brands/daihatsu.png",'img_dark' => null, 'name' => 'Daihatsu', 'alias' => null, 'popular'=> false],
            ['id' => 32, 'img_light' => "brands/daimler.png",'img_dark' => null, 'name' => 'Daimler', 'alias' => null, 'popular'=> false],
            ['id' => 33, 'img_light' => "brands/datsun.png",'img_dark' => null, 'name' => 'Datsun', 'alias' => null, 'popular'=> true],
            ['id' => 34, 'img_light' => null,'img_dark' => null, 'name' => 'Dayun', 'alias' => null, 'popular'=> false],
            ['id' => 35, 'img_light' => "brands/derways.png",'img_dark' => null, 'name' => 'Derways', 'alias' => null, 'popular'=> false],
            ['id' => 36, 'img_light' => "brands/dodge-light.png",'img_dark' => "brands/dodge-dark.png", 'name' => 'Dodge', 'alias' => null, 'popular'=> false],
            ['id' => 37, 'img_light' => "brands/dongfeng.png",'img_dark' => null, 'name' => 'Dongfeng', 'alias' => null, 'popular'=> false],
            ['id' => 38, 'img_light' => "brands/dw-hower.png",'img_dark' => null, 'name' => 'DW Hower', 'alias' => null, 'popular'=> false],
            ['id' => 39, 'img_light' => "brands/exeed.png",'img_dark' => null, 'name' => 'EXEED', 'alias' => null, 'popular'=> true],
            ['id' => 40, 'img_light' => "brands/faw.png",'img_dark' => null, 'name' => 'FAW', 'alias' => null, 'popular'=> true],
            ['id' => 41, 'img_light' => "brands/ferrari.png",'img_dark' => null, 'name' => 'Ferrari', 'alias' => null, 'popular'=> false],
            ['id' => 42, 'img_light' => "brands/fiat.png",'img_dark' => null, 'name' => 'Fiat', 'alias' => null, 'popular'=> false],
            ['id' => 43, 'img_light' => "brands/ford.png",'img_dark' => null, 'name' => 'Ford', 'alias' => null, 'popular'=> true],
            ['id' => 44, 'img_light' => "brands/forthing.png",'img_dark' => null, 'name' => 'Forthing', 'alias' => null, 'popular'=> false],
            ['id' => 45, 'img_light' => "brands/foton.png",'img_dark' => null, 'name' => 'Foton', 'alias' => null, 'popular'=> false],
            ['id' => 46, 'img_light' => "brands/gac.png",'img_dark' => null, 'name' => 'GAC', 'alias' => null, 'popular'=> false],
            ['id' => 47, 'img_light' => "brands/geely.png",'img_dark' => null, 'name' => 'Geely', 'alias' => null, 'popular'=> true],
            ['id' => 48, 'img_light' => "brands/genesis.png",'img_dark' => null, 'name' => 'Genesis', 'alias' => null, 'popular'=> false],
            ['id' => 49, 'img_light' => "brands/geo.png",'img_dark' => null, 'name' => 'Geo', 'alias' => null, 'popular'=> false],
            ['id' => 50, 'img_light' => "brands/gmc.png",'img_dark' => null, 'name' => 'GMC', 'alias' => null, 'popular'=> false],
            ['id' => 51, 'img_light' => "brands/great-wall.png",'img_dark' => null, 'name' => 'Great Wall', 'alias' => null, 'popular'=> false],
            ['id' => 52, 'img_light' => "brands/hafei.png",'img_dark' => null, 'name' => 'Hafei', 'alias' => null, 'popular'=> false],
            ['id' => 53, 'img_light' => "brands/haima.png",'img_dark' => null, 'name' => 'Haima', 'alias' => null, 'popular'=> false],
            ['id' => 54, 'img_light' => "brands/haval.png",'img_dark' => null, 'name' => 'Haval', 'alias' => null, 'popular'=> true],
            ['id' => 55, 'img_light' => "brands/hawtai.png",'img_dark' => null, 'name' => 'Hawtai', 'alias' => null, 'popular'=> false],
            ['id' => 56, 'img_light' => "brands/hiphi-light.png",'img_dark' => "brands/hiphi-dark.png", 'name' => 'HiPhi', 'alias' => null, 'popular'=> false],
            ['id' => 57, 'img_light' => "brands/honda.png",'img_dark' => null, 'name' => 'Honda', 'alias' => null, 'popular'=> true],
            ['id' => 58, 'img_light' => "brands/hongqi.png",'img_dark' => null, 'name' => 'Hongpi', 'alias' => null, 'popular'=> false],
            ['id' => 59, 'img_light' => "brands/hozon-light.png",'img_dark' => "brands/hozon-dark.png", 'name' => 'Hozon', 'alias' => null, 'popular'=> false],
            ['id' => 60, 'img_light' => "brands/hummer-light.png",'img_dark' => "brands/hummer-dark.png", 'name' => 'Hummer', 'alias' => null, 'popular'=> false],
            ['id' => 61, 'img_light' => "brands/hyundai.png",'img_dark' => null, 'name' => 'Hyundai', 'alias' => null, 'popular'=> true],
            ['id' => 62, 'img_light' => null,'img_dark' => null, 'name' => 'IM Motors', 'alias' => null, 'popular'=> false],
            ['id' => 63, 'img_light' => "brands/infiniti.png",'img_dark' => null, 'name' => 'Infiniti', 'alias' => null, 'popular'=> false],
            ['id' => 64, 'img_light' => "brands/iran-khobro.png",'img_dark' => null, 'name' => 'Iran Khodro', 'alias' => null, 'popular'=> false],
            ['id' => 65, 'img_light' => "brands/isuzu.png",'img_dark' => null, 'name' => 'Isuzu', 'alias' => null, 'popular'=> false],
            ['id' => 66, 'img_light' => null,'img_dark' => null, 'name' => 'IVECO', 'alias' => null, 'popular'=> false],
            ['id' => 67, 'img_light' => "brands/jac.png",'img_dark' => null, 'name' => 'JAC', 'alias' => null, 'popular'=> false],
            ['id' => 68, 'img_light' => null,'img_dark' => null, 'name' => 'Jaecco', 'alias' => null, 'popular'=> false],
            ['id' => 69, 'img_light' => "brands/jaguar.png",'img_dark' => null, 'name' => 'Jaguar', 'alias' => null, 'popular'=> false],
            ['id' => 70, 'img_light' => "brands/jeep.png",'img_dark' => null, 'name' => 'Jeep', 'alias' => null, 'popular'=> false],
            ['id' => 71, 'img_light' => "brands/jetour-light.png",'img_dark' => "brands/jetour-dark.png", 'name' => 'Jetour', 'alias' => null, 'popular'=> false],
            ['id' => 72, 'img_light' => "brands/jetta-light.png",'img_dark' => "brands/jetta-dark.png", 'name' => 'Jetta', 'alias' => null, 'popular'=> false],
            ['id' => 73, 'img_light' => null,'img_dark' => null, 'name' => 'Jindei', 'alias' => null, 'popular'=> false],
            ['id' => 74, 'img_light' => "brands/kaiyi-light.png",'img_dark' => "brands/kaiyi-dark.png", 'name' => 'Kaiyi', 'alias' => null, 'popular'=> false],
            ['id' => 75, 'img_light' => "brands/kia-light.png",'img_dark' => "brands/kia-dark.png", 'name' => 'Kia', 'alias' => null, 'popular'=> true],
            ['id' => 76, 'img_light' => "brands/lamborghini.png",'img_dark' => null, 'name' => 'Lamborghini', 'alias' => null, 'popular'=> false],
            ['id' => 77, 'img_light' => "brands/lancia.png",'img_dark' => null, 'name' => 'Lancia', 'alias' => null, 'popular'=> false],
            ['id' => 78, 'img_light' => "brands/land-rover.png",'img_dark' => null, 'name' => 'Land Rover', 'alias' => null, 'popular'=> true],
            ['id' => 79, 'img_light' => null,'img_dark' => null, 'name' => 'Landwind', 'alias' => null, 'popular'=> false],
            ['id' => 80, 'img_light' => null,'img_dark' => null, 'name' => 'Leapmotor', 'alias' => null, 'popular'=> false],
            ['id' => 81, 'img_light' => "brands/lexus.png",'img_dark' => null, 'name' => 'Lexus', 'alias' => null, 'popular'=> false],
            ['id' => 82, 'img_light' => "brands/li-light.png",'img_dark' => "brands/li-dark.png", 'name' => 'Li', 'alias' => null, 'popular'=> false],
            ['id' => 83, 'img_light' => "brands/lifan.png",'img_dark' => null, 'name' => 'Lifan', 'alias' => null, 'popular'=> true],
            ['id' => 84, 'img_light' => "brands/lincoln-light.png",'img_dark' => "brands/lincoln-dark.png", 'name' => 'Lincoln', 'alias' => null, 'popular'=> false],
            ['id' => 85, 'img_light' => "brands/livan-light.png",'img_dark' => "brands/livan-dark.png", 'name' => 'Livan', 'alias' => null, 'popular'=> false],
            ['id' => 86, 'img_light' => "brands/lotus.png",'img_dark' => null, 'name' => 'Lotus', 'alias' => null, 'popular'=> false],
            ['id' => 87, 'img_light' => "brands/luxgen.png",'img_dark' => null, 'name' => 'Luxgen', 'alias' => null, 'popular'=> false],
            ['id' => 88, 'img_light' => "brands/lynk_and_co-light.png",'img_dark' => "brands/lynk_and_co-dark.png", 'name' => 'Lynk & Co', 'alias' => null, 'popular'=> false],
            ['id' => 89, 'img_light' => "brands/maserati-light.png",'img_dark' => "brands/maserati-dark.png", 'name' => 'Maserati', 'alias' => null, 'popular'=> false],
            ['id' => 90, 'img_light' => null,'img_dark' => null, 'name' => 'Maxus', 'alias' => null, 'popular'=> false],
            ['id' => 91, 'img_light' => "brands/maybach.png",'img_dark' => null, 'name' => 'Maybach', 'alias' => null, 'popular'=> false],
            ['id' => 92, 'img_light' => "brands/mazda.png",'img_dark' => null, 'name' => 'Mazda', 'alias' => null, 'popular'=> true],
            ['id' => 93, 'img_light' => "brands/mclaren-light.png",'img_dark' => "brands/mclaren-dark.png", 'name' => 'McLaren', 'alias' => null, 'popular'=> false],
            ['id' => 94, 'img_light' => "brands/mercedes-benz.png",'img_dark' => null, 'name' => 'Mercedes-Benz', 'alias' => null, 'popular'=> true],
            ['id' => 95, 'img_light' => "brands/mercury.png",'img_dark' => null, 'name' => 'Mercury', 'alias' => null, 'popular'=> false],
            ['id' => 96, 'img_light' => "brands/mg-light.png",'img_dark' => "brands/mg-dark.png", 'name' => 'MG', 'alias' => null, 'popular'=> false],
            ['id' => 97, 'img_light' => "brands/mini-light.png",'img_dark' => "brands/mini-dark.png", 'name' => 'Mini', 'alias' => null, 'popular'=> false],
            ['id' => 98, 'img_light' => "brands/mitsubishi.png",'img_dark' => null, 'name' => 'Mitsubishi', 'alias' => null, 'popular'=> true],
            ['id' => 99, 'img_light' => "brands/mitsuoka-light.png",'img_dark' => "brands/mitsuoka-dark.png", 'name' => 'Mitsuoka', 'alias' => null, 'popular'=> false],
            ['id' => 100, 'img_light' => "brands/nio-light.png",'img_dark' => "brands/nio-dark.png", 'name' => 'Nio', 'alias' => null, 'popular'=> false],
            ['id' => 101, 'img_light' => "brands/nissan-light.png",'img_dark' => "brands/nissan-dark.png", 'name' => 'Nissan', 'alias' => null, 'popular'=> true],
            ['id' => 102, 'img_light' => "brands/oldmobile.png",'img_dark' => null, 'name' => 'Oldmobile', 'alias' => null, 'popular'=> false],
            ['id' => 103, 'img_light' => "brands/omoda-light.png",'img_dark' => "brands/omoda-dark.png", 'name' => 'OMODA', 'alias' => null, 'popular'=> true],
            ['id' => 104, 'img_light' => "brands/opel-light.png",'img_dark' => "brands/opel-dark.png", 'name' => 'Opel', 'alias' => null, 'popular'=> true],
            ['id' => 105, 'img_light' => null,'img_dark' => null, 'name' => 'Oshan', 'alias' => null, 'popular'=> false],
            ['id' => 106, 'img_light' => "brands/peugeot.png",'img_dark' => null, 'name' => 'Peugeot', 'alias' => null, 'popular'=> true],
            ['id' => 107, 'img_light' => "brands/plymouth.png",'img_dark' => null, 'name' => 'Plymouth', 'alias' => null, 'popular'=> false],
            ['id' => 108, 'img_light' => "brands/polestar.png",'img_dark' => null, 'name' => 'Polestar', 'alias' => null, 'popular'=> false],
            ['id' => 109, 'img_light' => "brands/pontiac-light.png",'img_dark' => "brands/pontiac-dark.png", 'name' => 'Pontiac', 'alias' => null, 'popular'=> false],
            ['id' => 110, 'img_light' => "brands/porsche.png",'img_dark' => null, 'name' => 'Porsche', 'alias' => null, 'popular'=> false],
            ['id' => 111, 'img_light' => "brands/proton.png",'img_dark' => null, 'name' => 'Proton', 'alias' => null, 'popular'=> false],
            ['id' => 112, 'img_light' => "brands/ram.png",'img_dark' => null, 'name' => 'RAM', 'alias' => null, 'popular'=> false],
            ['id' => 113, 'img_light' => "brands/ravon.png",'img_dark' => null, 'name' => 'Ravon', 'alias' => null, 'popular'=> false],
            ['id' => 114, 'img_light' => "brands/renault-light.png",'img_dark' => "brands/renault-dark.png", 'name' => 'Renault', 'alias' => null, 'popular'=> true],
            ['id' => 115, 'img_light' => "brands/renault-samsung.png",'img_dark' => null, 'name' => 'Renault Samsung', 'alias' => null, 'popular'=> false],
            ['id' => 116, 'img_light' => null,'img_dark' => null, 'name' => 'Rising Auto', 'alias' => null, 'popular'=> false],
            ['id' => 117, 'img_light' => "brands/roewe-light.png",'img_dark' => "brands/roewe-dark.png", 'name' => 'Roewe', 'alias' => null, 'popular'=> false],
            ['id' => 118, 'img_light' => "brands/rolls-royce.png",'img_dark' => null, 'name' => 'Rolls-Royse', 'alias' => null, 'popular'=> false],
            ['id' => 119, 'img_light' => "brands/rover.png",'img_dark' => null, 'name' => 'Rover', 'alias' => null, 'popular'=> false],
            ['id' => 120, 'img_light' => "brands/saab.png",'img_dark' => null, 'name' => 'Saab', 'alias' => null, 'popular'=> false],
            ['id' => 121, 'img_light' => "brands/saturn.png",'img_dark' => null, 'name' => 'Saturn', 'alias' => null, 'popular'=> false],
            ['id' => 122, 'img_light' => "brands/scion.png",'img_dark' => null, 'name' => 'Scion', 'alias' => null, 'popular'=> false],
            ['id' => 123, 'img_light' => "brands/seat.png",'img_dark' => null, 'name' => 'SEAT', 'alias' => null, 'popular'=> false],
            ['id' => 124, 'img_light' => null,'img_dark' => null, 'name' => 'Seres', 'alias' => null, 'popular'=> false],
            ['id' => 125, 'img_light' => "brands/shuanghuan.png",'img_dark' => null, 'name' => 'Shuanghuan', 'alias' => null, 'popular'=> false],
            ['id' => 126, 'img_light' => "brands/skoda.png",'img_dark' => null, 'name' => 'Skoda', 'alias' => null, 'popular'=> true],
            ['id' => 127, 'img_light' => "brands/skywell.png",'img_dark' => null, 'name' => 'Skywell', 'alias' => null, 'popular'=> false],
            ['id' => 128, 'img_light' => "brands/smart.png",'img_dark' => null, 'name' => 'Smart', 'alias' => null, 'popular'=> false],
            ['id' => 129, 'img_light' => "brands/soueart.png",'img_dark' => null, 'name' => 'Soueart', 'alias' => null, 'popular'=> false],
            ['id' => 130, 'img_light' => "brands/ssangyong.png",'img_dark' => null, 'name' => 'SsangYong', 'alias' => null, 'popular'=> false],
            ['id' => 131, 'img_light' => "brands/subaru.png",'img_dark' => null, 'name' => 'Subaru', 'alias' => null, 'popular'=> true],
            ['id' => 132, 'img_light' => "brands/suzuki.png",'img_dark' => null, 'name' => 'Suzuki', 'alias' => null, 'popular'=> true],
            ['id' => 133, 'img_light' => "brands/tank-light.png",'img_dark' => "brands/tank-dark.png", 'name' => 'Tank', 'alias' => null, 'popular'=> false],
            ['id' => 134, 'img_light' => "brands/tesla.png",'img_dark' => null, 'name' => 'Tesla', 'alias' => null, 'popular'=> false],
            ['id' => 135, 'img_light' => "brands/tianma.png",'img_dark' => null, 'name' => 'Tianma', 'alias' => null, 'popular'=> false],
            ['id' => 136, 'img_light' => "brands/toyota-light.png",'img_dark' => "brands/toyota-dark.png", 'name' => 'Toyota', 'alias' => null, 'popular'=> true],
            ['id' => 137, 'img_light' => null,'img_dark' => null, 'name' => 'Venicia', 'alias' => null, 'popular'=> false],
            ['id' => 138, 'img_light' => "brands/volkswagen.png",'img_dark' => null, 'name' => 'Volkswagen', 'alias' => null, 'popular'=> true],
            ['id' => 139, 'img_light' => "brands/volvo-light.png",'img_dark' => "brands/volvo-dark.png", 'name' => 'Volvo', 'alias' => null, 'popular'=> true],
            ['id' => 140, 'img_light' => "brands/vortex-light.png",'img_dark' => "brands/vortex-dark.png", 'name' => 'Vortex', 'alias' => null, 'popular'=> false],
            ['id' => 141, 'img_light' => "brands/voyah-light.png",'img_dark' => "brands/voyah-dark.png",  'name' => 'Voyah', 'alias' => null, 'popular'=> false],
            ['id' => 142, 'img_light' => "brands/weltmeister-light.png",'img_dark' => "brands/weltmeister-dark.png",  'name' => 'Weltmeister', 'alias' => null, 'popular'=> false],
            ['id' => 143, 'img_light' => null,'img_dark' => null, 'name' => 'WEY', 'alias' => null, 'popular'=> false],
            ['id' => 144, 'img_light' => null,'img_dark' => null, 'name' => 'Wuling', 'alias' => null, 'popular'=> false],
            ['id' => 145, 'img_light' => "brands/xin-kai-light.png",'img_dark' => "brands/xin-kai-dark.png",  'name' => 'Xin Kai', 'alias' => null, 'popular'=> false],
            ['id' => 146, 'img_light' => "brands/xpeng-light.png",'img_dark' => "brands/xpeng-dark.png",  'name' => 'Xpeng', 'alias' => null, 'popular'=> false],
            ['id' => 147, 'img_light' => "brands/zeekr-light.png",'img_dark' => "brands/zeekr-dark.png",  'name' => 'Zeekr', 'alias' => null, 'popular'=> false],
            ['id' => 148, 'img_light' => "brands/zotye.png",'img_dark' => null, 'name' => 'Zotye', 'alias' => null, 'popular'=> false],
            ['id' => 149, 'img_light' => "brands/zx.png",'img_dark' => null, 'name' => 'ZX', 'alias' => null, 'popular'=> false],
            ['id' => 150, 'img_light' => "brands/evolute-light.png",'img_dark' => "brands/evolute-dark.png", 'name' => 'Evolute', 'alias' => null, 'popular'=> false],
            ['id' => 151, 'img_light' => "brands/aurus.png",'img_dark' => null, 'name' => 'Аурус', 'alias' => null, 'popular'=> false],
            ['id' => 152, 'img_light' => "brands/bogdan.png",'img_dark' => null, 'name' => 'Богдан', 'alias' => null, 'popular'=> false],
            ['id' => 153, 'img_light' => "brands/gaz.png",'img_dark' => null, 'name' => 'ГАЗ', 'alias' => null, 'popular'=> true],
            ['id' => 154, 'img_light' => "brands/doninvest.png",'img_dark' => null, 'name' => 'Донинвест', 'alias' => null, 'popular'=> false],
            ['id' => 155, 'img_light' => "brands/zaz.png",'img_dark' => null, 'name' => 'ЗАЗ', 'alias' => null, 'popular'=> true],
            ['id' => 156, 'img_light' => "brands/zil-light.png",'img_dark' => "brands/zil-dark.png", 'name' => 'ЗИЛ', 'alias' => null, 'popular'=> false],
            ['id' => 157, 'img_light' => null,'img_dark' => null, 'name' => 'ЗиС', 'alias' => null, 'popular'=> false],
            ['id' => 158, 'img_light' => "brands/izh.png",'img_dark' => null, 'name' => 'ИЖ', 'alias' => null, 'popular'=> false],
            ['id' => 159, 'img_light' => "brands/lada.png",'img_dark' => null, 'name' => 'Лада', 'alias' => null, 'popular'=> true],
            ['id' => 160, 'img_light' => "brands/luaz.png",'img_dark' => null, 'name' => 'ЛуАЗ', 'alias' => null, 'popular'=> false],
            ['id' => 161, 'img_light' => "brands/moskvich.png",'img_dark' => null, 'name' => 'Москвич', 'alias' => null, 'popular'=> false],
            ['id' => 162, 'img_light' => "brands/tagaz.png",'img_dark' => null, 'name' => 'ТагАЗ', 'alias' => null, 'popular'=> false],
            ['id' => 163, 'img_light' => "brands/uaz.png",'img_dark' => null, 'name' => 'УАЗ', 'alias' => null, 'popular'=> true],
            ['id' => 164, 'img_light' => null,'img_dark' => null, 'name' => 'Прочие авто', 'alias' => null, 'popular'=> false],
        ];

        DB::table('brands')->insert($brand);
    }
}
