<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WidgetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    { 
        $transmission = [
            [
                'id'=> 1, 
                'name' => "BrandColumnWidget", 
                'specification'=>'Колонки_с_брендами',
                'status_main'=>null,
                'position_main'=>null,
                'status_product'=>null,
                'position_product'=>null,
                'status_list_products'=>null,
                'position_list_products'=>null,
                'status_catalog'=>null,
                'position_catalog'=>null,
                'status_client_cabinet'=>null,
                'position_client_cabinet'=>null,
            ],
            [
                'id'=> 2, 
                'name' => "CaruselWidget", 
                'specification'=>'Карусель',
                'status_main'=>'on',
                'position_main'=>'hero-top-two',
                'status_product'=>null,
                'position_product'=>null,
                'status_list_products'=>null,
                'position_list_products'=>null,
                'status_catalog'=>null,
                'position_catalog'=>null,
                'status_client_cabinet'=>null,
                'position_client_cabinet'=>null,
            ],
            [
                'id'=> 3, 
                'name' => "LoginRegisterWidget", 
                'specification'=>'Логин/пароль',
                'status_main'=>'on',
                'position_main'=>'header-panel-right',
                'status_product'=>null,
                'position_product'=>null,
                'status_list_products'=>null,
                'position_list_products'=>null,
                'status_catalog'=>null,
                'position_catalog'=>null,
                'status_client_cabinet'=>null,
                'position_client_cabinet'=>null,
            ],
            [
                'id'=> 4, 
                'name' => "RelevanceProductWidget", 
                'specification'=>'Актуальный_продукт',
                'status_main'=>'on',
                'position_main'=>'content-top-one',
                'status_product'=>null,
                'position_product'=>null,
                'status_list_products'=>null,
                'position_list_products'=>null,
                'status_catalog'=>null,
                'position_catalog'=>null,
                'status_client_cabinet'=>null,
                'position_client_cabinet'=>null,
            ],
            [
                'id'=> 5, 
                'name' => "ReviewsOwnersWidget", 
                'specification'=>'Отзывы_владельцев',
                'status_main'=>'on',
                'position_main'=>'',
                'status_product'=>null,
                'position_product'=>null,
                'status_list_products'=>null,
                'position_list_products'=>null,
                'status_catalog'=>null,
                'position_catalog'=>null,
                'status_client_cabinet'=>null,
                'position_client_cabinet'=>null,
            ],
            [
                'id'=> 6, 
                'name' => "MenuWidget", 
                'specification'=>'Меню',
                'status_main'=>null,
                'position_main'=>'header-panel-center',
                'status_product'=>null,
                'position_product'=>null,
                'status_list_products'=>null,
                'position_list_products'=>null,
                'status_catalog'=>null,
                'position_catalog'=>null,
                'status_client_cabinet'=>null,
                'position_client_cabinet'=>null,
            ],
            [
                'id'=> 7, 
                'name' => "LocationWidget", 
                'specification'=>'Локация',
                'status_main'=>null,
                'position_main'=>'header-panel-left',
                'status_product'=>null,
                'position_product'=>null,
                'status_list_products'=>null,
                'position_list_products'=>null,
                'status_catalog'=>null,
                'position_catalog'=>null,
                'status_client_cabinet'=>null,
                'position_client_cabinet'=>null,
            ],
            [
                'id'=> 8, 
                'name' => "CheckBeforePurchaseWidget", 
                'specification'=>'Проверка_авто_перед_покупкой',
                'status_main'=>null,
                'position_main'=>'extra-top-one',
                'status_product'=>null,
                'position_product'=>null,
                'status_list_products'=>null,
                'position_list_products'=>null,
                'status_catalog'=>null,
                'position_catalog'=>null,
                'status_client_cabinet'=>null,
                'position_client_cabinet'=>null,
            ],
            [
                'id'=> 9, 
                'name' => "LocalCityWidget", 
                'specification'=>'Локализация_по_городу',
                'status_main'=>'on',
                'position_main'=>'hero-top-one',
                'status_product'=>null,
                'position_product'=>null,
                'status_list_products'=>null,
                'position_list_products'=>null,
                'status_catalog'=>null,
                'position_catalog'=>null,
                'status_client_cabinet'=>null,
                'position_client_cabinet'=>null,
            ],
        ];
        DB::table('widgets')->insert($transmission);
    }
}
